AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation Template to create basic EC2 Instance.
Resources:
 SimpleEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
   ImageId: ami-041d6256ed0f2061c
   InstanceType: t2.micro
 
 
 