AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation Template to create S3 bucket using Parameters.
Parameters:
 CFnS3BucketName:
   Type: String
   Description: Enter Bucket Name
   Default: cfn-s3-bucket-2021-19-10
Resources:
 SimpleS3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Ref CFnS3BucketName
 
